import shutil
import os
import glob
import argparse


def clean_proj():
    try:
        shutil.rmtree('./solver')
    except Exception as e:
        print('Warning: {}'.format(e))
    try:
        shutil.rmtree('./optimize')
    except Exception as e:
        print('Warning: {}'.format(e))
    try:
        shutil.rmtree('./misfits')
    except Exception as e:
        print('Warning: {}'.format(e))
    for fname in glob.glob('./output_fwat*.txt'):
        os.remove(fname)


def main():
    parser = argparse.ArgumentParser('Clean all output (solver/, optimize/, misfits/, and output_fwat*.txt) generated by FWAT')
    parser.add_argument('-f', help='Force clean, never prompt', action='store_true', default=False)
    args = parser.parse_args()
    if not args.f:
        clstr = input('Remove solver/, optimize/, misfits/, and output_fwat*.txt in this folder? [y/n]: ')
        if clstr.lower() == 'y':
            isclean = True
        else:
            isclean = False
    else:
        isclean = True
    if isclean:
        clean_proj()
